const List<String> jobsTitleForFetching = [
  "developer",
  "software developer",
  "front-end developer",
  "back-end developer",
  "full-stack developer",
  "mobile developer",
  "android developer",
  "iOS developer",
  "web developer",
  "UX/UI designer",
  "quality assurance",
  "QA engineer",
  "software engineer",
  "system analyst",
  "data scientist",
  "data analyst",
  "machine learning engineer",
  "artificial intelligence engineer",
  "AI engineer",
  "cloud engineer",
  "DevOps engineer",
  "network engineer",
  "cybersecurity specialist",
  "security analyst",
  "blockchain developer",
  "database administrator",
  "DBA",
  "IT support specialist",
  "IT administrator",
  "IT consultant",
  "technical writer",
  "game developer",
  "embedded systems developer",
  "firmware developer",
  "application developer",
  "technical project manager",
  "solutions architect",
  "site reliability engineer",
  "SRE",
  "big data engineer",
  "ETL developer",
  "software architect",
  "scrum master",
  "technical lead",
  "programmer",
  "application engineer",
  "help desk technician",
  "IT technician",
  "robotics engineer",
  "systems engineer",
  "VR/AR developer",
  "IT auditor",
  "penetration tester",
  "information security manager",
  "cloud architect",
  "CRM developer",
  "ERP consultant"
];
